spring.application.name=multi-threaded-file-processing-system
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.web=DEBUG
spring.servlet.multipart.location=/tmp/spring-uploads
spring.servlet.multipart.file-size-threshold=2MB
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level){highlight} %clr(%logger{20}){blue} %clr(:){faint} %msg%n
